name: Sync labels
on:
  push:
    branches: [ main, master ]
    paths:
      - '.github/labels.yml'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
